# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfaa5e3ed650e29d185b525850953bdbc66c010c27fa206ccbdf6ea5f482e8319136ba9440d946214a9be3ef33b558bb381bc23ceaeca089343931ff5b9eb434

test:
  secret_key_base: 29e7e3c91ea0fddd560b82f6d22efd1e9946ff933dd96ec3b3d1e797500b47cfcb04e4fa9e98e47995c9c5a9da6180694e2a64dba1807f3b463f2c029e477f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
